server:
  port: 8080
  servlet:
    context-path: /api/@api.version@

game:
  port: 2000
  players: 4

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Who-Am-I
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
