server:
  port: 8080
  servlet:
    context-path: /api/@api.version@

game:
  port: 2000
  players: 4

spring:
  datasource:
    url: jdbc:postgresql://postgresql-132317-0.cloudclusters.net:10002/Who_Am_I
    username: user
    password: userAdmin
  jpa:
    hibernate:
      ddl-auto: validate
